### ISSUE TITLE
Clarification on licensing

### ISSUE THREAD

**Issue by lucyydotp** [destruc7i0n/vscode-bedrock-definitions#12]
Hi there, 

I'm unsure as to what this plugin is licensed under - your package.json specifies MIT but the license file is GPL3. Could you please confirm which license is correct?

**Comment by destruc7i0n** [comment]
I believe GPL3. I'll update the package.json to remove any confusion.

**Comment by lucyydotp** [comment]
Nice, thanks for confirming!
