### ISSUE TITLE
"minecraft:player.saturation" "max" is marked as not allowed

### ISSUE THREAD

**Issue by DrinkWater623** [destruc7i0n/vscode-bedrock-definitions#16]
in player.json:
"minecraft:player.saturation": {
        "value": 5,
        "max": 20
      },
it says max is not allowed.  But it is, it is in the Vanilla Pack

**Comment by destruc7i0n** [comment]
This extension does not provide any JSON schema for entity json files - you might be using the Blockception plugin, in which case you should file an issue in https://github.com/Blockception/Minecraft-bedrock-json-schemas

**Comment by DrinkWater623** [comment]
Sorry... I just followed the links here, did not know I was in the wrong place...and of course from the wrong extension.. sorry again, can you delete it if I can't?

**Comment by destruc7i0n** [comment]
No problem!
