### ISSUE TITLE
Go-to definitions don't work for mcfunction files with capital letters in their path/filename

### ISSUE THREAD

**Issue by Dwittyy** [destruc7i0n/vscode-bedrock-definitions#9]
Suppose I have a function with the file path `examples/MyFunction`. While this is a valid function name, it doesn't get recognised as a go-to definition.

Looks like the function path matching here isn't including capital letters in the list of the allowed characters? (I'm not sure if functions are the only file types in Minecraft that allow capitals)
https://github.com/destruc7i0n/vscode-bedrock-definitions/blob/a2ee7a6188b601903418392b112d9bc8c94065a9/src/lib/LineParser.ts#L8-L9

**Comment by destruc7i0n** [comment]
Fixed! Thanks for the report. At the time of creation, I did not know capital letters were supported in bedrock functions.
